/**
 * CCCS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cccs);
  }
}(this, function(expect, Cccs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cccs.ProjectsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectsApi', function() {
    describe('apiProjectCreate', function() {
      it('should call apiProjectCreate successfully', function(done) {
        //uncomment below and update the code to test apiProjectCreate
        //instance.apiProjectCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiProjectDelete', function() {
      it('should call apiProjectDelete successfully', function(done) {
        //uncomment below and update the code to test apiProjectDelete
        //instance.apiProjectDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiProjectGet', function() {
      it('should call apiProjectGet successfully', function(done) {
        //uncomment below and update the code to test apiProjectGet
        //instance.apiProjectGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiProjectGetOne', function() {
      it('should call apiProjectGetOne successfully', function(done) {
        //uncomment below and update the code to test apiProjectGetOne
        //instance.apiProjectGetOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiProjectPut', function() {
      it('should call apiProjectPut successfully', function(done) {
        //uncomment below and update the code to test apiProjectPut
        //instance.apiProjectPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
