/**
 * CCCS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cccs);
  }
}(this, function(expect, Cccs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cccs.SubmissionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SubmissionsApi', function() {
    describe('apiSubmissionCreate', function() {
      it('should call apiSubmissionCreate successfully', function(done) {
        //uncomment below and update the code to test apiSubmissionCreate
        //instance.apiSubmissionCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiSubmissionDelete', function() {
      it('should call apiSubmissionDelete successfully', function(done) {
        //uncomment below and update the code to test apiSubmissionDelete
        //instance.apiSubmissionDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiSubmissionGet', function() {
      it('should call apiSubmissionGet successfully', function(done) {
        //uncomment below and update the code to test apiSubmissionGet
        //instance.apiSubmissionGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiSubmissionGetOne', function() {
      it('should call apiSubmissionGetOne successfully', function(done) {
        //uncomment below and update the code to test apiSubmissionGetOne
        //instance.apiSubmissionGetOne(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiSubmissionPut', function() {
      it('should call apiSubmissionPut successfully', function(done) {
        //uncomment below and update the code to test apiSubmissionPut
        //instance.apiSubmissionPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
