/**
 * CCCS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Cccs);
  }
}(this, function(expect, Cccs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Cccs.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('apiOtokenGenerate', function() {
      it('should call apiOtokenGenerate successfully', function(done) {
        //uncomment below and update the code to test apiOtokenGenerate
        //instance.apiOtokenGenerate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserGet', function() {
      it('should call apiUserGet successfully', function(done) {
        //uncomment below and update the code to test apiUserGet
        //instance.apiUserGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserGetUsers', function() {
      it('should call apiUserGetUsers successfully', function(done) {
        //uncomment below and update the code to test apiUserGetUsers
        //instance.apiUserGetUsers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserLogin', function() {
      it('should call apiUserLogin successfully', function(done) {
        //uncomment below and update the code to test apiUserLogin
        //instance.apiUserLogin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiUserRegister', function() {
      it('should call apiUserRegister successfully', function(done) {
        //uncomment below and update the code to test apiUserRegister
        //instance.apiUserRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('decoratorsAccessChecksEnsureKey', function() {
      it('should call decoratorsAccessChecksEnsureKey successfully', function(done) {
        //uncomment below and update the code to test decoratorsAccessChecksEnsureKey
        //instance.decoratorsAccessChecksEnsureKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
