/**
 * CCCS
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Media'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Media'));
  } else {
    // Browser globals (root is window)
    if (!root.Cccs) {
      root.Cccs = {};
    }
    root.Cccs.MediaApi = factory(root.Cccs.ApiClient, root.Cccs.Media);
  }
}(this, function(ApiClient, Media) {
  'use strict';

  /**
   * Media service.
   * @module api/MediaApi
   * @version 0.1
   */

  /**
   * Constructs a new MediaApi. 
   * @alias module:api/MediaApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the apiMediaCreate operation.
     * @callback module:api/MediaApi~apiMediaCreateCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a new media attachment
     * @param {File} attachment The file to be uploaded
     * @param {Object} opts Optional parameters
     * @param {module:model/Media} opts.media 
     * @param {module:api/MediaApi~apiMediaCreateCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.apiMediaCreate = function(attachment, opts, callback) {
      opts = opts || {};
      var postBody = opts['media'];

      // verify the required parameter 'attachment' is set
      if (attachment === undefined || attachment === null) {
        throw new Error("Missing the required parameter 'attachment' when calling apiMediaCreate");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'attachment': attachment
      };

      var authNames = ['apiKeyHeader'];
      var contentTypes = ['multipart/form-data'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/media', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
